version: "2.0"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - 3306:3306
    volumes:
      - ./forma1.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forma1
    cap_add:
      - SYS_NICE
